#!/usr/bin/env bash
#
# Builds one environment from nothing to a working entry point.
#
# It exists because the alternative is a person typing the same six commands
# in the same order, and the last time that happened the commands were the only
# record of how the thing was built. Everything here is either in this
# repository or derived from the stack's own outputs; nothing is typed twice.
#
# Usage: ./bootstrap.sh dev
#
# Prerequisites: terraform apply has already run for this environment, and
# gcloud is authenticated as somebody who can read the cluster.

set -euo pipefail

ENV="${1:?usage: bootstrap.sh <environment>}"

# Pinned deliberately. Taking whatever is newest means the cluster built today
# and the cluster built next month run different code, and the difference is
# discovered when one of them behaves differently.
CERT_MANAGER_VERSION="v1.21.1"

HERE="$(cd "$(dirname "$0")" && pwd)"
OVERLAY="${HERE}/../platform/edge/overlays/${ENV}"

if [ ! -d "$OVERLAY" ]; then
  echo "No overlay for environment '${ENV}' at ${OVERLAY}" >&2
  exit 1
fi

echo "==> Reading the stack's outputs"
OUTPUTS="$(terraform -chdir="$HERE" output -json environments)"

# A missing output has to stop this script rather than produce an empty value.
#
# Command substitution inside a heredoc swallows a non-zero exit: the document
# is still written, with a blank where the value should be, and the manifests
# are applied with nothing in the field. set -e does not catch it. So every
# value is read into a variable first and checked before anything is written.
read_value() {
  local value
  value="$(echo "$OUTPUTS" | python3 -c "import json,sys; print(json.load(sys.stdin)['${ENV}'].get('$1',''))")"
  if [ -z "$value" ]; then
    echo "The stack has no output '$1' for environment '${ENV}'." >&2
    echo "If the outputs were changed since the last apply, run terraform apply." >&2
    exit 1
  fi
  printf '%s' "$value"
}

PROJECT="$(read_value project)"
CLUSTER="$(read_value cluster)"
ZONE="$(read_value zone)"
WILDCARD="$(read_value wildcard)"
DOMAIN_FILTER="$(read_value dns_domain)"
DNS_PROJECT="$(read_value dns_project)"
DNS_SA="$(read_value dns_service_account)"
ACME_EMAIL="$(read_value acme_email)"

# The manifests' values are generated rather than filled in, so the only place
# an environment is described is the Terraform variables file. A value that is
# typed in two places is a value that will disagree with itself.
echo "==> Generating ${OVERLAY}/values.env"
cat > "${OVERLAY}/values.env" <<EOF
# Generated by lab/bootstrap.sh. Do not edit: change the Terraform variables
# and run it again.
wildcard=${WILDCARD}
domainFilter=${DOMAIN_FILTER}
dnsProject=${DNS_PROJECT}
txtOwnerId=${CLUSTER}
dnsServiceAccount=${DNS_SA}
acmeEmail=${ACME_EMAIL}
EOF

echo "==> Fetching cluster credentials"
gcloud container clusters get-credentials "$CLUSTER" --zone "$ZONE" --project "$PROJECT" >/dev/null 2>&1

echo "==> Installing cert-manager ${CERT_MANAGER_VERSION}"
# Its custom resources have to be registered before anything that uses them,
# which is why this is a separate step and not another entry in the overlay.
helm repo add jetstack https://charts.jetstack.io >/dev/null 2>&1
helm repo update >/dev/null 2>&1
helm upgrade --install cert-manager jetstack/cert-manager \
  --version "$CERT_MANAGER_VERSION" \
  --namespace cert-manager --create-namespace \
  --set crds.enabled=true \
  --set "serviceAccount.annotations.iam\.gke\.io/gcp-service-account=${DNS_SA}" \
  --wait --timeout 8m >/dev/null

echo "==> Applying the edge"
kubectl apply -k "$OVERLAY"

echo "==> Waiting for the certificate"
# The entry point is built by the platform and takes minutes. While it is being
# built it exists and answers nothing, which looks like a broken configuration
# and is not.
kubectl -n gateway wait --for=condition=Ready certificate/edge-tls --timeout=10m || {
  echo "The certificate is not ready yet. This is usually the DNS challenge" >&2
  echo "still propagating; check with:" >&2
  echo "  kubectl -n gateway describe certificate edge-tls" >&2
  exit 1
}

echo
echo "Done. The entry point is:"
kubectl -n gateway get gateway edge -o jsonpath='{.status.addresses[0].value}'
echo
