#!/usr/bin/env bash
#
# Builds one environment from nothing to a working entry point.
#
# It exists because the alternative is a person typing the same six commands
# in the same order, and the last time that happened the commands were the only
# record of how the thing was built. Everything here is either in this
# repository or derived from the stack's own outputs; nothing is typed twice.
#
# Usage: ./bootstrap.sh dev
#
# Prerequisites: terraform apply has already run for this environment, and
# gcloud is authenticated as somebody who can read the cluster.

set -euo pipefail

ENV="${1:?usage: bootstrap.sh <environment>}"

# Pinned deliberately. Taking whatever is newest means the cluster built today
# and the cluster built next month run different code, and the difference is
# discovered when one of them behaves differently.
CERT_MANAGER_VERSION="v1.21.1"

HERE="$(cd "$(dirname "$0")" && pwd)"
OVERLAY="${HERE}/../platform/edge/overlays/${ENV}"

if [ ! -d "$OVERLAY" ]; then
  echo "No overlay for environment '${ENV}' at ${OVERLAY}" >&2
  exit 1
fi

# Every call below crosses a link that may be slow and jittery rather than
# broken. Long operations over one connection time out on such a link while
# short ones succeed, so the failure looks intermittent and is not random: it
# is the long ones. Retrying is the honest response, and each step here is
# idempotent by construction so retrying is safe.
retry() {
  local attempts="$1" description="$2"
  shift 2
  local i
  for i in $(seq 1 "$attempts"); do
    if "$@"; then
      return 0
    fi
    [ "$i" -lt "$attempts" ] && echo "    ${description}: attempt ${i} failed, retrying"
    sleep $(( i * 10 ))
  done
  echo "${description}: gave up after ${attempts} attempts" >&2
  return 1
}

echo "==> Reading the stack's outputs"
OUTPUTS="$(terraform -chdir="$HERE" output -json environments)"

# A missing output has to stop this script rather than produce an empty value.
#
# Command substitution inside a heredoc swallows a non-zero exit: the document
# is still written, with a blank where the value should be, and the manifests
# are applied with nothing in the field. set -e does not catch it. So every
# value is read into a variable first and checked before anything is written.
read_value() {
  local value
  value="$(echo "$OUTPUTS" | python3 -c "import json,sys; print(json.load(sys.stdin)['${ENV}'].get('$1',''))")"
  if [ -z "$value" ]; then
    echo "The stack has no output '$1' for environment '${ENV}'." >&2
    echo "If the outputs were changed since the last apply, run terraform apply." >&2
    exit 1
  fi
  printf '%s' "$value"
}

PROJECT="$(read_value project)"
CLUSTER="$(read_value cluster)"
ZONE="$(read_value zone)"
REGISTRY="$(terraform -chdir="$HERE" output -raw registry)"
WILDCARD="$(read_value wildcard)"
DOMAIN_FILTER="$(read_value dns_domain)"
DNS_PROJECT="$(read_value dns_project)"
DNS_SA="$(read_value dns_service_account)"
ACME_EMAIL="$(read_value acme_email)"
SECURITY_POLICY="$(read_value security_policy)"

# The manifests' values are generated rather than filled in, so the only place
# an environment is described is the Terraform variables file. A value that is
# typed in two places is a value that will disagree with itself.
DOMAIN="$DOMAIN_FILTER"

write_values() {
  local dir="$1" host="$2"
  mkdir -p "$dir"
  cat > "${dir}/values.env" <<EOF
# Generated by lab/bootstrap.sh. Do not edit: change the Terraform variables
# and run it again.
wildcard=${WILDCARD}
host=${host}
domainFilter=${DOMAIN}
dnsProject=${DNS_PROJECT}
txtOwnerId=${CLUSTER}
dnsServiceAccount=${DNS_SA}
acmeEmail=${ACME_EMAIL}
securityPolicy=${SECURITY_POLICY}
EOF
}

echo "==> Generating the values every overlay reads"
write_values "${HERE}/../platform/edge/overlays/${ENV}"        "edge.${DOMAIN}"
write_values "${HERE}/../platform/n8n/overlays/${ENV}"         "n8n.${DOMAIN}"
write_values "${HERE}/../platform/vaultwarden/overlays/${ENV}" "vault.${DOMAIN}"
write_values "${HERE}/../platform/erpnext/overlays/${ENV}"     "erp.${DOMAIN}"

# The password manager builds links from the address it believes it is on. One
# that disagrees with the route produces a login page redirecting somewhere
# that is not there.
cat > "${HERE}/../platform/vaultwarden/overlays/${ENV}/vaultwarden.env" <<EOF
domain=https://vault.${DOMAIN}
smtp_host=localhost
smtp_from=vaultwarden@${DOMAIN}
EOF

echo "==> Fetching cluster credentials"
gcloud container clusters get-credentials "$CLUSTER" --zone "$ZONE" --project "$PROJECT" >/dev/null 2>&1

echo "==> Installing cert-manager ${CERT_MANAGER_VERSION}"
# Its custom resources have to be registered before anything that uses them,
# which is why this is a separate step and not another entry in the overlay.
INSTALLED="$(helm -n cert-manager list -f '^cert-manager$' -o json 2>/dev/null \
  | python3 -c "import json,sys; r=json.load(sys.stdin); print(r[0]['chart'] if r else '')" 2>/dev/null || true)"

if [ "$INSTALLED" = "cert-manager-${CERT_MANAGER_VERSION}" ]; then
  echo "    already at ${CERT_MANAGER_VERSION}, left alone"
else
  helm repo add jetstack https://charts.jetstack.io >/dev/null 2>&1
  helm repo update >/dev/null 2>&1
  retry 3 "cert-manager" helm upgrade --install cert-manager jetstack/cert-manager \
    --version "$CERT_MANAGER_VERSION" \
    --namespace cert-manager --create-namespace \
    --set crds.enabled=true \
    --set "serviceAccount.annotations.iam\.gke\.io/gcp-service-account=${DNS_SA}" \
    --wait --timeout 10m >/dev/null
fi

echo "==> Copying images into the repository this estate holds"
# Nothing here is built. Every workload is somebody else's image, which makes
# where it is pulled from a decision rather than a detail.
#
# The copy runs as a build inside the platform, not here. Copying through this
# machine was the first attempt and it was wrong: source and destination are
# both remote, so every byte crossed the operator's link twice and one image
# took over an hour. It also hit the public registry's anonymous rate limit,
# which the platform's own fetch does not.
#
# It is skipped when every image is already held, because the copy is the slow
# part and it only has to happen when an image in the list changes.
IMAGES_FILE="${HERE}/../platform/images.env"

# Associative arrays need a shell newer than the one macOS ships, and a script
# that only runs on the author's machine is not automation.
pinned_set() { eval "PINNED_$1=\"$2\""; }
pinned_get() { eval "printf '%s' \"\${PINNED_$1}\""; }

held_everything() {
  while IFS='=' read -r name upstream; do
    case "$name" in ''|\#*) continue ;; esac
    crane digest "${REGISTRY}/apps/${name}:${upstream##*:}" >/dev/null 2>&1 || return 1
  done < "$IMAGES_FILE"
  return 0
}

if ! command -v crane >/dev/null 2>&1; then
  echo "crane is required to read image digests. Install it from" >&2
  echo "  https://github.com/google/go-containerregistry" >&2
  exit 1
fi

gcloud auth configure-docker "$(echo "$REGISTRY" | cut -d/ -f1)" --quiet >/dev/null 2>&1

if held_everything; then
  echo "    every image is already held, skipping the copy"
else
  echo "    submitting the copy; this is slow the first time and only the first"
  retry 2 "image copy" gcloud builds submit "${HERE}/../platform" \
    --config="${HERE}/../platform/promote-images.yaml" \
    --substitutions="_REGISTRY=${REGISTRY}" \
    --project="$(echo "$REGISTRY" | cut -d/ -f2)" \
    --quiet >/dev/null
fi

echo "==> Resolving what will be deployed"
# The tag says which image was asked for. The digest is the image, and it is
# what goes into the manifests: a tag is a pointer somebody can move.
while IFS='=' read -r name upstream; do
  case "$name" in ''|\#*) continue ;; esac
  ref="${REGISTRY}/apps/${name}:${upstream##*:}"
  digest=""
  for attempt in 1 2 3; do
    if digest="$(crane digest "$ref" 2>/dev/null)" && [ -n "$digest" ]; then
      break
    fi
    echo "    ${name}: not resolved on attempt ${attempt}, retrying"
    sleep $(( attempt * 10 ))
  done
  if [ -z "$digest" ]; then
    echo "Could not resolve ${ref}." >&2
    exit 1
  fi
  pinned_set "$name" "${REGISTRY}/apps/${name}@${digest}"
  echo "    ${name} -> ${digest}"
done < "$IMAGES_FILE"

# The image each overlay deploys is written here rather than pinned in the
# manifests, because a digest is not something a person should be maintaining
# by hand in four files.
echo "==> Writing the pinned images into the overlays"

cat > "${HERE}/../platform/n8n/overlays/${ENV}/images.yaml" <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: n8n
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-db
          image: $(pinned_get postgres)
      containers:
        - name: n8n
          image: $(pinned_get n8n)
EOF

cat > "${HERE}/../platform/n8n/overlays/${ENV}/images-postgres.yaml" <<EOF
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: n8n
spec:
  template:
    spec:
      containers:
        - name: postgres
          image: $(pinned_get postgres)
EOF

cat > "${HERE}/../platform/vaultwarden/overlays/${ENV}/images.yaml" <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  template:
    spec:
      containers:
        - name: vaultwarden
          image: $(pinned_get vaultwarden)
EOF

# Secrets are generated here and created directly, never written to a file in
# the repository and never passed through a deployment tool's values. ADR 22.
#
# A real estate takes these from a secret manager. Generating them is right for
# something meant to be destroyed and wrong for anything that has to survive:
# n8n's encryption key in particular cannot be regenerated on a live system
# without losing every stored credential, and here it is regenerated on every
# fresh cluster on purpose.
ensure_secret() {
  local ns="$1" name="$2"
  shift 2
  kubectl create namespace "$ns" >/dev/null 2>&1 || true
  if kubectl -n "$ns" get secret "$name" >/dev/null 2>&1; then
    echo "    secret ${ns}/${name} already exists, left alone"
  else
    kubectl -n "$ns" create secret generic "$name" "$@" >/dev/null
    echo "    created secret ${ns}/${name}"
  fi
}

echo "==> Secrets"
ensure_secret n8n n8n \
  --from-literal=db-password="$(openssl rand -hex 24)" \
  --from-literal=encryption-key="$(openssl rand -hex 32)"

# Mail does not work in the lab and this secret exists only because the
# deployment requires it to start. Invitations and password hints will fail,
# which is a lab limitation rather than a configuration to copy.
ensure_secret vaultwarden vaultwarden-smtp \
  --from-literal=username="unused-in-lab" \
  --from-literal=password="unused-in-lab"

echo "==> The edge"
# The entry point, the record publisher and the certificate issuer's
# configuration. It comes before the workloads because their routes attach to
# the Gateway this creates, and a route whose parent does not exist is accepted
# and does nothing.
retry 3 "edge manifests" kubectl apply -k "$OVERLAY"

echo "==> Storage classes"
# The password manager's volume asks for an encrypted class by name rather than
# taking the cluster's default, so that the choice is visible in the manifest.
# The class has to exist before anything claims it, and a claim naming a class
# that is absent stays pending forever with no event explaining why.
retry 3 "storage class" kubectl apply -f "${HERE}/../platform/storage/encrypted-standard.yaml"

echo "==> Shared storage for the ERP"
# The sites directory is written by the web process, the scheduler and every
# background worker, and they do not share a node. It needs ReadWriteMany, and
# none of the platform's own storage classes offer it.
sed "s|storageClassName: REPLACE_ME|storageClassName: standard-rwo|" \
  "${HERE}/../platform/erpnext/storage/nfs-server.yaml" | kubectl apply -f - >/dev/null
kubectl -n storage rollout status deployment/nfs-provisioner --timeout=5m

echo "==> n8n"
retry 3 "n8n manifests" kubectl apply -k "${HERE}/../platform/n8n/overlays/${ENV}"

echo "==> Vaultwarden"
retry 3 "vaultwarden manifests" kubectl apply -k "${HERE}/../platform/vaultwarden/overlays/${ENV}"

echo "==> ERPNext"
# The image comes from the registry this estate controls rather than from the
# internet at deploy time. ADR 12: the remote repository is a caching proxy, so
# the name changes and the content does not.
helm repo add frappe https://helm.erpnext.com >/dev/null 2>&1
helm repo update >/dev/null 2>&1
ERP_TAG="$(grep '^erpnext=' "$IMAGES_FILE" | sed 's/.*://')"
ERP_HOST="erp.${DOMAIN}"

# The database passwords are created once and referenced, never passed.
#
# Two reasons, and the second is the one that bit. A password supplied as a
# chart value is stored with the release history in the cluster, in clear, so
# anyone who can read secrets in the namespace can recover it, including after
# the person who set it has left. And a value generated fresh on every run
# disagrees with the one already stored, which the chart refuses with an error
# about a missing key rather than about a changed password.
#
# Creating the secret first fixes both: the chart never holds the value, and a
# second run finds what the first one made.
# The name is ours rather than the one the chart would generate. Helm refuses
# to adopt an object it did not create, so a secret sharing the templated name
# blocks the install with a message about ownership metadata rather than about
# the name.
ensure_secret erp erp-db-credentials \
  --from-literal=mariadb-root-password="$(openssl rand -hex 24)" \
  --from-literal=mariadb-password="$(openssl rand -hex 24)" \
  --from-literal=mariadb-replication-password="$(openssl rand -hex 24)"

# The site's administrator password has the same problem and one more: it
# cannot be read back from the application afterwards, only replaced. Keeping
# it here means a second run does not silently create a second one that is
# never used.
ensure_secret erp erp-site-admin \
  --from-literal=password="$(openssl rand -hex 12)"

ERP_ADMIN="$(kubectl -n erp get secret erp-site-admin -o jsonpath='{.data.password}' | base64 -d)"

# Whether the site already exists decides whether the creation job should run
# at all. Asking for it again on a bench that has it is a job that fails and
# stays red.
if kubectl -n erp get job -l "app.kubernetes.io/name=erpnext" 2>/dev/null | grep -q new-site; then
  CREATE_SITE=false
  echo "    a site creation job already ran; not asking for another"
else
  CREATE_SITE=true
fi

# The alias mariadb.enabled exists for backward compatibility; the values the
# database subchart actually reads live under its real name, which is why the
# secret is set under mariadb-subchart rather than mariadb.
helm upgrade --install erp frappe/erpnext \
  --namespace erp --create-namespace \
  --values "${HERE}/../platform/erpnext/helm/values.yaml" \
  --set "persistence.worker.storageClass=nfs" \
  --set "persistence.logs.storageClass=nfs" \
  --set "image.repository=${REGISTRY}/apps/erpnext" \
  --set "image.tag=${ERP_TAG}" \
  --set "mariadb.enabled=true" \
  --set "mariadb-subchart.auth.existingSecret=erp-db-credentials" \
  --set "dbHost=erp-mariadb" \
  --set "jobs.createSite.enabled=${CREATE_SITE}" \
  --set "jobs.createSite.siteName=${ERP_HOST}" \
  --set "jobs.createSite.adminPassword=${ERP_ADMIN}" \
  --timeout 20m --wait=false >/dev/null
retry 3 "erpnext manifests" kubectl apply -k "${HERE}/../platform/erpnext/overlays/${ENV}"

# The administrative password is set when the site is created and cannot be
# read back afterwards, only replaced. It is printed once, here, because the
# alternative is that nobody can get in.
echo
echo "    ERP administrator password is in the secret erp/erp-site-admin:"
echo "      kubectl -n erp get secret erp-site-admin -o jsonpath='{.data.password}' | base64 -d"
echo "    The application cannot give it back, only take a new one:"
echo "      kubectl -n erp exec deploy/erp-erpnext-conf-bench -- bench --site ${ERP_HOST} set-admin-password <new>"
echo

echo "==> Waiting for the certificate"
# The entry point is built by the platform and takes minutes. While it is being
# built it exists and answers nothing, which looks like a broken configuration
# and is not.
kubectl -n gateway wait --for=condition=Ready certificate/edge-tls --timeout=10m || {
  echo "The certificate is not ready yet. This is usually the DNS challenge" >&2
  echo "still propagating; check with:" >&2
  echo "  kubectl -n gateway describe certificate edge-tls" >&2
  exit 1
}

echo
echo "Done. The entry point is:"
kubectl -n gateway get gateway edge -o jsonpath='{.status.addresses[0].value}'
echo
